"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Navbar from "@/components/layout/Navbar";
import { getDashboard, getProjects, getTeamMembers } from "@/lib/api";
import { getUser } from "@/lib/auth";

const labels = { DRAFT: "Draft", SUBMITTED: "Submitted", NEEDS_CORRECTION: "Needs correction", APPROVED: "Approved" };

export default function SummaryPage() {
  const router = useRouter();
  const [data, setData] = useState(null), [projects, setProjects] = useState([]), [members, setMembers] = useState([]);
  const [filters, setFilters] = useState({ weekStart: "", weekEnd: "", memberId: "", projectId: "", status: "" });
  const [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const load = async (active = filters) => { setLoading(true); setError(""); try { setData(await getDashboard(active)); } catch (err) { setError(err.message || "Could not load the team summary."); } finally { setLoading(false); } };
  useEffect(() => { const user = getUser(); if (!user) return router.replace("/login"); if (!["MANAGER", "ADMIN"].includes(user.role)) return router.replace("/weeklyreport"); Promise.all([load(), getProjects(), getTeamMembers()]).then(([, p, m]) => { setProjects(p); setMembers(m); }).catch((err) => setError(err.message)); }, [router]);
  const update = (name, value) => setFilters((current) => ({ ...current, [name]: value }));
  const stats = data?.stats || {}, rows = data?.members || [];
  return <div className="min-h-screen bg-stone-50 text-gray-900"><Navbar /><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
    <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-serif">Team insights</h1><p className="mt-1 text-sm text-gray-500">Report health, workload, and review activity.</p></div><button onClick={() => load()} className="rounded-md border border-gray-300 bg-white px-3 py-2 text-sm hover:bg-gray-50">Refresh</button></div>
    <form onSubmit={(event) => { event.preventDefault(); load(); }} className="mb-6 grid grid-cols-1 gap-3 border border-gray-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-6"><input aria-label="Start date" type="date" value={filters.weekStart} onChange={(event) => update("weekStart", event.target.value)} className="rounded-md border border-gray-300 px-3 py-2 text-sm" /><input aria-label="End date" type="date" value={filters.weekEnd} onChange={(event) => update("weekEnd", event.target.value)} className="rounded-md border border-gray-300 px-3 py-2 text-sm" /><Select value={filters.memberId} onChange={(event) => update("memberId", event.target.value)} empty="All members" items={members.map((item) => [item.id, item.name])} /><Select value={filters.projectId} onChange={(event) => update("projectId", event.target.value)} empty="All projects" items={projects.map((item) => [item.id, item.name])} /><Select value={filters.status} onChange={(event) => update("status", event.target.value)} empty="All statuses" items={Object.entries(labels)} /><button className="rounded-md bg-orange-700 px-4 py-2 text-sm font-medium text-white hover:bg-orange-800">Apply filters</button></form>
    {error && <div className="mb-6 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <section className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Submitted" value={stats.totalSubmittedThisWeek || 0} note="in selected range" /><Metric label="Compliance" value={`${stats.complianceRate || 0}%`} note={`${stats.notStarted || 0} not started`} /><Metric label="Needs correction" value={stats.needsCorrectionCount || 0} note="awaiting updates" /><Metric label="Open blockers" value={stats.openBlockersCount || 0} note={`${stats.totalHours || 0} team hours`} /></section>
    <section className="mb-6 grid gap-6 lg:grid-cols-2"><Panel title="Tasks completed over time"><Bars data={data?.tasksTrend} labelKey="label" valueKey="value" /></Panel><Panel title="Time by task type"><Bars data={data?.timeByType} labelKey="taskType" valueKey="hours" alternate /></Panel><Panel title="Workload by project"><Bars data={data?.projectWorkload} labelKey="project" valueKey="totalHours" /></Panel><Panel title="Recent activity"><div className="space-y-3">{(data?.recentActivity || []).length ? data.recentActivity.map((item) => <button key={item.id} onClick={() => router.push(`/review/${item.reportId}`)} className="block w-full border-b border-gray-100 pb-3 text-left text-sm hover:text-orange-700"><span className="font-medium">{item.memberName}</span> {item.action.toLowerCase().replace("_", " ")}<span className="block text-xs text-gray-500">{item.comment || (item.createdAt ? new Date(item.createdAt).toLocaleString() : "")}</span></button>) : <Empty />}</div></Panel></section>
    <section className="overflow-hidden border border-gray-200 bg-white"><div className="border-b border-gray-200 px-4 py-3"><h2 className="font-semibold">Reports</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-gray-500"><tr><th className="px-4 py-3">Member</th><th className="px-4 py-3">Project</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Tasks</th><th className="px-4 py-3">Hours</th><th className="px-4 py-3"></th></tr></thead><tbody>{loading ? <tr><td colSpan="6" className="p-8 text-center text-gray-500">Loading reports...</td></tr> : rows.length ? rows.map((row) => <tr key={row.reportId} className="border-t border-gray-100"><td className="px-4 py-3 font-medium">{row.memberName}</td><td className="px-4 py-3">{projects.find((project) => project.id === row.projectId)?.name || "Unassigned"}</td><td className="px-4 py-3"><Status value={row.status} /></td><td className="px-4 py-3">{row.completedTasks}/{row.totalTasks}</td><td className="px-4 py-3">{row.totalHours}h</td><td className="px-4 py-3 text-right"><button onClick={() => router.push(`/review/${row.reportId}`)} className="text-orange-700 hover:underline">Open</button></td></tr>) : <tr><td colSpan="6" className="p-8 text-center text-gray-500">No reports match these filters.</td></tr>}</tbody></table></div></section>
  </main></div>;
}
function Select({ value, onChange, empty, items }) { return <select value={value} onChange={onChange} className="rounded-md border border-gray-300 bg-white px-3 py-2 text-sm"><option value="">{empty}</option>{items.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>; }
function Metric({ label, value, note }) { return <div className="border border-gray-200 bg-white p-4"><p className="text-xs text-gray-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-gray-500">{note}</p></div>; }
function Panel({ title, children }) { return <section className="border border-gray-200 bg-white p-5"><h2 className="mb-4 font-semibold">{title}</h2>{children}</section>; }
function Empty() { return <p className="py-6 text-center text-sm text-gray-500">No data for this range.</p>; }
function Status({ value }) { const colors = { APPROVED: "bg-green-100 text-green-700", SUBMITTED: "bg-blue-100 text-blue-700", NEEDS_CORRECTION: "bg-red-100 text-red-700", DRAFT: "bg-gray-100 text-gray-700" }; return <span className={`inline-block rounded-full px-2 py-1 text-xs ${colors[value] || colors.DRAFT}`}>{labels[value] || value}</span>; }
function Bars({ data = [], labelKey, valueKey, alternate }) { const maximum = Math.max(...data.map((item) => Number(item[valueKey]) || 0), 1); if (!data.length) return <Empty />; return <div className="space-y-3">{data.map((item) => <div key={item[labelKey]}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="truncate">{item[labelKey]}</span><span>{item[valueKey]}</span></div><div className="h-2 bg-gray-100"><div className={alternate ? "h-full bg-teal-600" : "h-full bg-orange-600"} style={{ width: `${(Number(item[valueKey]) / maximum) * 100}%` }} /></div></div>)}</div>; }
